# NAVEGADOR
webdriver.driver=firefox
firefox.options.args=--private

# ? CONFIGURACIÓN CRÍTICA - AUMENTAR TIEMPOS
serenity.timeout=30000
webdriver.wait.for.timeout=30000
webdriver.timeouts.implicitlywait=10000

# ? FORZAR REINTENTOS
serenity.restart.browser.for.each=scenario
serenity.use.unique.browser=true
serenity.webdriver.clear.cookies=each